import {
  Contract,
  Supplier,
  NotificationItem,
  AuditLog,
  SystemSettings,
  UserAccountItem,
  UserProfile,
  ApiKeyItem,
  WebhookItem,
  IntegrationConnector,
  GranularPermission,
} from './types';

const CARLOS_AVATAR = 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80';

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-aws',
    cnpj: '23.412.348/0001-90',
    razaoSocial: 'Amazon Web Services Brasil Ltda.',
    nomeFantasia: 'AWS Cloud Brasil',
    inscricaoEstadual: '114.890.312.110',
    contactName: 'Mariana Drummond',
    contactRole: 'Enterprise Account Executive',
    contactEmail: 'drummond.aws@amazon.com',
    contactPhone: '(11) 3958-4000',
    activities: ['Computação em Nuvem', 'Hospedagem de Dados', 'Serviços de Infraestrutura IA'],
    riskLevel: 'baixo',
    activeContractsCount: 1,
    totalFinancialVolume: 420000,
    status: 'ativo',
    syncDate: 'Hoje às 09:30',
  },
  {
    id: 'sup-msft',
    cnpj: '60.316.817/0001-03',
    razaoSocial: 'Microsoft Informática Ltda.',
    nomeFantasia: 'Microsoft Brasil',
    inscricaoEstadual: '111.452.980.119',
    contactName: 'Carlos Eduardo Nogueira',
    contactRole: 'Diretor de Contas Enterprise',
    contactEmail: 'cnogueira@microsoft.com',
    contactPhone: '(11) 4871-1500',
    activities: ['Licenciamento SaaS', 'Produtividade Office 365', 'Segurança Corporativa'],
    riskLevel: 'baixo',
    activeContractsCount: 1,
    totalFinancialVolume: 180000,
    status: 'ativo',
    syncDate: 'Ontem',
  },
  {
    id: 'sup-totvs',
    cnpj: '53.113.791/0001-22',
    razaoSocial: 'TOTVS S.A.',
    nomeFantasia: 'TOTVS Soluções Corporativas',
    inscricaoEstadual: '112.983.471.115',
    contactName: 'Renata Vasconcellos',
    contactRole: 'Gerente de Atendimento RioMais',
    contactEmail: 'renata.vasconcellos@totvs.com.br',
    contactPhone: '(11) 2099-7000',
    activities: ['ERP Protheus', 'Folha de Pagamento', 'Módulos Fiscais'],
    riskLevel: 'medio',
    activeContractsCount: 1,
    totalFinancialVolume: 96000,
    status: 'ativo',
    syncDate: 'Há 2 dias',
  },
  {
    id: 'sup-sap',
    cnpj: '00.741.056/0001-92',
    razaoSocial: 'SAP Brasil Ltda.',
    nomeFantasia: 'SAP Enterprise Software',
    inscricaoEstadual: '115.002.391.114',
    contactName: 'Roberto Silveira',
    contactRole: 'VP de Negócios Brasil',
    contactEmail: 'roberto.silveira@sap.com',
    contactPhone: '(11) 5503-2400',
    activities: ['ERP S/4HANA Cloud', 'Módulos de Compras Ariba', 'BI & Analytics'],
    riskLevel: 'baixo',
    activeContractsCount: 1,
    totalFinancialVolume: 1250000,
    status: 'ativo',
    syncDate: 'Esta semana',
  },
  {
    id: 'sup-google',
    cnpj: '06.990.590/0001-23',
    razaoSocial: 'Google Cloud Brasil Internet Ltda.',
    nomeFantasia: 'Google Cloud Platform',
    inscricaoEstadual: '117.842.193.116',
    contactName: 'Juliana Paes de Barros',
    contactRole: 'Key Account Manager',
    contactEmail: 'jbarros@google.com',
    contactPhone: '(11) 2395-6000',
    activities: ['Vertex AI', 'BigQuery', 'Google Workspace Enterprise'],
    riskLevel: 'baixo',
    activeContractsCount: 1,
    totalFinancialVolume: 260000,
    status: 'homologacao',
    syncDate: 'Hoje às 08:15',
  },
  {
    id: 'sup-deloitte',
    cnpj: '49.928.567/0001-11',
    razaoSocial: 'Deloitte Touche Tohmatsu Consultores Ltda.',
    nomeFantasia: 'Deloitte Consultoria',
    inscricaoEstadual: '113.840.119.112',
    contactName: 'André Figueiredo',
    contactRole: 'Sócio-Líder Governança & LGPD',
    contactEmail: 'afigueiredo@deloitte.com.br',
    contactPhone: '(11) 5186-1000',
    activities: ['Auditoria Independente', 'Conformidade LGPD', 'Cibersegurança'],
    riskLevel: 'medio',
    activeContractsCount: 1,
    totalFinancialVolume: 145000,
    status: 'ativo',
    syncDate: 'Há 3 dias',
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'ctr-aws-2025',
    code: 'CTR-2025-842',
    internalId: '#8420-25',
    title: 'Prestação de Serviços de Computação em Nuvem e Infraestrutura AWS',
    supplierId: 'sup-aws',
    supplierName: 'Amazon Web Services Brasil Ltda.',
    supplierCnpj: '23.412.348/0001-90',
    category: 'Infraestrutura / Cloud',
    startDate: '2025-01-15',
    endDate: '2027-01-15',
    totalDays: 730,
    remainingDays: 312,
    totalValue: 420000,
    monthlyValue: 17500,
    periodicity: 'mensal',
    status: 'vigente',
    signatureStatus: 'Assinado Digitalmente (ICP-Brasil)',
    hasOcr: true,
    progressPercent: 57,
    isSigned: true,
    signedDate: '15/01/2025',
    signingMethod: 'DocuSign Enterprise (ICP-Brasil A3)',
    notificationEmail: 'ti.contratos@gruporiomais.com.br',
    notifyOnExpiration: true,
    notifyOnStatusChange: true,
    signers: [
      {
        id: 's-lucas',
        name: 'Lucas Teles',
        role: 'Diretor Jurídico & CLO',
        cpf: '***.382.918-**',
        signed: true,
        signedAt: '15/01/2025 às 14:20',
        avatarInitials: 'LT',
      },
      {
        id: 's-drummond',
        name: 'Mariana Drummond',
        role: 'Procuradora AWS Brasil',
        cpf: '***.194.208-**',
        signed: true,
        signedAt: '15/01/2025 às 16:45',
        avatarInitials: 'MD',
      },
    ],
    attachments: [
      {
        id: 'att-aws-1',
        name: 'Contrato_Master_AWS_2025_Assinado.pdf',
        size: '3.4 MB',
        addedAt: '15/01/2025',
        type: 'pdf',
        description: 'Via assinada com carimbo do tempo e hash forense',
      },
    ],
    aiInsights: {
      executiveSummary: 'Contrato de serviços em nuvem AWS corporativo cobrindo clusters de banco de dados, storage S3 e Kubernetes EKS com SLA garantido de 99.99%.',
      items: [
        { topic: 'SLA de Disponibilidade', summary: 'Garantia contratual de 99.99% uptime com créditos automáticos na fatura.', icon: 'verified' },
        { topic: 'Proteção de Dados', summary: 'Armazenamento estrito na região América do Sul (São Paulo sa-east-1) em conformidade com a LGPD.', icon: 'security' },
        { topic: 'Reajuste Anual', summary: 'Indexado ao IPCA com aviso prévio mínimo de 60 dias.', icon: 'payments' },
      ],
    },
  },
  {
    id: 'ctr-msft-2025',
    code: 'CTR-2025-104',
    internalId: '#1044-25',
    title: 'Acordo Enterprise de Licenciamento Microsoft 365 E5 e Serviços Azure',
    supplierId: 'sup-msft',
    supplierName: 'Microsoft Informática Ltda.',
    supplierCnpj: '60.316.817/0001-03',
    category: 'Software / SaaS',
    startDate: '2024-04-10',
    endDate: '2026-04-10',
    totalDays: 730,
    remainingDays: 22,
    totalValue: 180000,
    monthlyValue: 7500,
    periodicity: 'mensal',
    status: 'avencer',
    signatureStatus: 'Assinado Digitalmente',
    hasOcr: true,
    progressPercent: 97,
    isSigned: true,
    signedDate: '10/04/2024',
    signingMethod: 'Adobe Acrobat Sign Enterprise',
    notificationEmail: 'controladoria.contratos@gruporiomais.com.br',
    notifyOnExpiration: true,
    notifyOnStatusChange: true,
    signers: [
      {
        id: 's-lucas',
        name: 'Lucas Teles',
        role: 'Diretor Jurídico',
        cpf: '***.382.918-**',
        signed: true,
        signedAt: '10/04/2024 às 11:30',
        avatarInitials: 'LT',
      },
    ],
    attachments: [
      {
        id: 'att-msft-1',
        name: 'Termo_Licenciamento_M365_E5.pdf',
        size: '2.1 MB',
        addedAt: '10/04/2024',
        type: 'pdf',
        description: 'Acordo EA com 850 licenças corporativas ativas',
      },
    ],
    aiInsights: {
      executiveSummary: 'Instrumento contratual de 850 licenças Microsoft 365 E5 com segurança avançada Defender e serviços Azure. Vencimento próximo requer renovação ou aditamento.',
      items: [
        { topic: 'Vencimento Crítico', summary: 'Restam apenas 22 dias para término da vigência. Renovação prioritária.', icon: 'warning' },
        { topic: 'Penalidade de Interrupção', summary: 'Carência de 30 dias após término antes do desligamento do tenant corporativo.', icon: 'timer' },
      ],
      criticalRisk: 'Vencimento em menos de 30 dias sem protocolo formal de renovação registrado no ERP.',
    },
  },
  {
    id: 'ctr-sap-2025',
    code: 'CTR-2025-618',
    internalId: '#6180-25',
    title: 'Implementação e Suporte Contínuo do ERP Corporativo SAP S/4HANA Cloud',
    supplierId: 'sup-sap',
    supplierName: 'SAP Brasil Ltda.',
    supplierCnpj: '00.741.056/0001-92',
    category: 'ERP & Sistemas',
    startDate: '2025-02-01',
    endDate: '2028-02-01',
    totalDays: 1095,
    remainingDays: 240,
    totalValue: 1250000,
    monthlyValue: 34722,
    periodicity: 'mensal',
    status: 'vigente',
    signatureStatus: 'Assinado com Certificado A3 ICP-Brasil',
    hasOcr: true,
    progressPercent: 35,
    isSigned: true,
    signedDate: '01/02/2025',
    signingMethod: 'DocuSign ICP-Brasil',
    notificationEmail: 'juridico@gruporiomais.com.br',
    notifyOnExpiration: true,
    notifyOnStatusChange: true,
    signers: [
      {
        id: 's-lucas',
        name: 'Lucas Teles',
        role: 'Diretor Jurídico & Governança',
        cpf: '***.382.918-**',
        signed: true,
        signedAt: '01/02/2025',
        avatarInitials: 'LT',
      },
    ],
    attachments: [
      {
        id: 'att-sap-1',
        name: 'Contrato_S4HANA_Cloud_RioMais.pdf',
        size: '5.8 MB',
        addedAt: '01/02/2025',
        type: 'pdf',
      },
    ],
    aiInsights: {
      executiveSummary: 'Contrato plurianual de transformação digital e ERP com escopo de gestão financeira, fiscal, compras e suprimentos.',
      items: [
        { topic: 'Garantia de Manutenção', summary: 'Atendimento 24/7 para incidentes de severidade 1 com SLA de resposta de 1 hora.', icon: 'support_agent' },
      ],
    },
  },
  {
    id: 'ctr-totvs-2025',
    code: 'CTR-2025-391',
    internalId: '#3910-25',
    title: 'Sustentação Operacional de Módulos Legados TOTVS Protheus RH e Fiscal',
    supplierId: 'sup-totvs',
    supplierName: 'TOTVS S.A.',
    supplierCnpj: '53.113.791/0001-22',
    category: 'ERP & Sistemas',
    startDate: '2024-05-15',
    endDate: '2026-05-15',
    totalDays: 730,
    remainingDays: 48,
    totalValue: 96000,
    monthlyValue: 4000,
    periodicity: 'mensal',
    status: 'avencer',
    signatureStatus: 'Assinado Digitalmente',
    hasOcr: true,
    progressPercent: 93,
    isSigned: true,
    notificationEmail: 'rh.folha@gruporiomais.com.br',
    notifyOnExpiration: true,
    notifyOnStatusChange: true,
    signers: [
      {
        id: 's-lucas',
        name: 'Lucas Teles',
        role: 'Diretor Jurídico',
        cpf: '***.382.918-**',
        signed: true,
        avatarInitials: 'LT',
      },
    ],
    attachments: [],
    aiInsights: {
      executiveSummary: 'Contrato de suporte mensal de folha de pagamento e eSocial com prazo de expiração em 48 dias.',
      items: [
        { topic: 'Janela de Renovação', summary: 'Cláusula prevê renovação automática caso não haja descontinuidade notificada em 30 dias.', icon: 'update' },
      ],
    },
  },
  {
    id: 'ctr-google-2025',
    code: 'CTR-2025-905',
    internalId: '#9050-25',
    title: 'Termo de Prestação de Serviços Vertex AI e Google Cloud Data Analytics',
    supplierId: 'sup-google',
    supplierName: 'Google Cloud Brasil Internet Ltda.',
    supplierCnpj: '06.990.590/0001-23',
    category: 'Tecnologia / SaaS',
    startDate: '2025-06-01',
    endDate: '2026-06-01',
    totalDays: 365,
    remainingDays: 85,
    totalValue: 260000,
    periodicity: 'demanda',
    status: 'sem_assinatura',
    signatureStatus: 'Pendente de Assinatura pelo Jurídico',
    hasOcr: true,
    progressPercent: 0,
    isSigned: false,
    notificationEmail: 'juridico@gruporiomais.com.br',
    notifyOnExpiration: true,
    notifyOnStatusChange: true,
    signers: [
      {
        id: 's-lucas',
        name: 'Lucas Teles',
        role: 'Diretor Jurídico & CLO',
        cpf: '***.382.918-**',
        signed: false,
        avatarInitials: 'LT',
      },
    ],
    attachments: [
      {
        id: 'att-gcp-1',
        name: 'Minuta_Google_Vertex_AI_2025.pdf',
        size: '1.9 MB',
        addedAt: 'Hoje',
        type: 'pdf',
      },
    ],
    aiInsights: {
      executiveSummary: 'Minuta em fase final de validação jurídica para ativação de inteligência artificial generativa e analytics corporativo.',
      items: [
        { topic: 'Cláusula de IP', summary: 'Propriedade intelectual de dados e modelos treinados permanece 100% com o Grupo RioMais.', icon: 'auto_awesome' },
      ],
    },
  },
  {
    id: 'ctr-deloitte-2025',
    code: 'CTR-2025-442',
    internalId: '#4420-25',
    title: 'Consultoria de Adequação LGPD Contínua e Testes de Intrusão em Cibersegurança',
    supplierId: 'sup-deloitte',
    supplierName: 'Deloitte Touche Tohmatsu Consultores Ltda.',
    supplierCnpj: '49.928.567/0001-11',
    category: 'Consultoria & Auditoria',
    startDate: '2024-11-01',
    endDate: '2026-11-01',
    totalDays: 730,
    remainingDays: 235,
    totalValue: 145000,
    monthlyValue: 6041,
    periodicity: 'mensal',
    status: 'vigente',
    signatureStatus: 'Assinado Digitalmente',
    hasOcr: true,
    progressPercent: 68,
    isSigned: true,
    notificationEmail: 'compliance@gruporiomais.com.br',
    notifyOnExpiration: true,
    notifyOnStatusChange: true,
    signers: [
      {
        id: 's-lucas',
        name: 'Lucas Teles',
        role: 'Diretor Jurídico',
        cpf: '***.382.918-**',
        signed: true,
        avatarInitials: 'LT',
      },
    ],
    attachments: [],
    aiInsights: {
      executiveSummary: 'Auditoria de segurança independente e compliance de proteção de dados pessoais.',
      items: [
        { topic: 'Relatórios Trimestrais', summary: 'Emissão mandatória de laudos técnicos de segurança para o comitê de governança.', icon: 'assessment' },
      ],
    },
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Alerta de Vencimento Crítico: CTR-2025-104',
    description: 'Faltam 22 dias para o término do contrato com a Microsoft Informática Ltda. Ação de renovação recomendada.',
    timeAgo: 'Hoje às 08:30',
    type: 'expiracao',
    contractCode: 'CTR-2025-104',
    read: false,
    urgent: true,
    badgeText: '22 dias restantes',
    actionText: 'Ver contrato →',
  },
  {
    id: 'notif-2',
    title: 'Pendente de Assinatura Digital: CTR-2025-905',
    description: 'Minuta do contrato com o Google Cloud aguarda assinatura do Diretor Jurídico Lucas Teles.',
    timeAgo: 'Ontem às 16:45',
    type: 'assinatura',
    contractCode: 'CTR-2025-905',
    read: false,
    urgent: false,
    badgeText: 'Aguardando CLO',
    actionText: 'Assinar minuta →',
  },
  {
    id: 'notif-3',
    title: 'Alerta de Vencimento: CTR-2025-391 (48 dias)',
    description: 'Contrato de sustentação TOTVS ERP expira em 48 dias. Avaliar necessidade de termo aditivo.',
    timeAgo: 'Há 2 dias',
    type: 'expiracao',
    contractCode: 'CTR-2025-391',
    read: true,
    urgent: false,
    badgeText: '48 dias restantes',
    actionText: 'Ver detalhes →',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-101',
    user: 'Lucas Teles',
    userEmail: 'lucas.teles@gruporiomais.com.br',
    role: 'Administrador Geral',
    action: 'CONTRATO_REGISTRADO',
    detail: 'Registro e homologação inicial do contrato CTR-2025-842 com Amazon Web Services Brasil Ltda.',
    resource: 'CTR-2025-842',
    resourceType: 'contrato',
    resourceId: 'ctr-aws-2025',
    ip: '189.40.72.112',
    location: 'São Paulo, Brasil',
    timestamp: 'Hoje às 09:15',
    type: 'contract',
    severity: 'baixo',
    integrityHash: 'SHA256-A89F0B7C4123EA809B11',
  },
  {
    id: 'aud-102',
    user: 'Lucas Teles',
    userEmail: 'lucas.teles@gruporiomais.com.br',
    role: 'Administrador Geral',
    action: 'ALERTA_VENCIMENTO_SIMULADO',
    detail: 'Simulação preventiva de disparo de e-mail de término de vigência para o contrato CTR-2025-104 (22 dias restantes).',
    resource: 'CTR-2025-104',
    resourceType: 'contrato',
    resourceId: 'ctr-msft-2025',
    ip: '189.40.72.112',
    location: 'São Paulo, Brasil',
    timestamp: 'Hoje às 08:31',
    type: 'warning',
    severity: 'alto',
    integrityHash: 'SHA256-91FB4D88CA2044F00E8B',
  },
  {
    id: 'aud-103',
    user: 'Sistema Automático MaisContratos',
    userEmail: 'daemon@maiscontratos.riomais.com.br',
    role: 'CLM Monitor Engine',
    action: 'MONITORAMENTO_EXPIRACAO_EXECUTADO',
    detail: 'Rotina de conferência cronométrica de vigências executada com sucesso. 2 contratos identificados no horizonte crítico.',
    resource: 'Sistema',
    resourceType: 'sistema',
    ip: '127.0.0.1 (Localhost)',
    location: 'Data Center RioMais',
    timestamp: 'Hoje às 00:01',
    type: 'security',
    severity: 'baixo',
    integrityHash: 'SHA256-C4B089AE319980FA1288',
  },
];

export const INITIAL_USERS: UserAccountItem[] = [
  {
    id: 'usr-lucas-teles',
    name: 'Lucas Teles',
    email: 'lucas.teles@gruporiomais.com.br',
    department: 'Diretoria Jurídica & Governança',
    jobTitle: 'Diretor Jurídico Corporativo',
    phone: '+55 (11) 98112-4090',
    documentNumber: '341.890.112-45',
    matricula: 'RIO-0012',
    role: 'administrador',
    status: 'ativo',
    twoFactorEnabled: true,
    lastLogin: 'Hoje às 09:40',
    createdAt: '10/01/2024',
  },
  {
    id: 'usr-ana-souza',
    name: 'Ana Beatriz Souza',
    email: 'ana.souza@gruporiomais.com.br',
    department: 'Controladoria e Suprimentos',
    jobTitle: 'Gerente de Contratos & Suprimentos',
    phone: '+55 (11) 97230-5541',
    documentNumber: '289.443.001-92',
    matricula: 'RIO-0145',
    role: 'editor',
    status: 'ativo',
    twoFactorEnabled: true,
    lastLogin: 'Hoje às 08:15',
    createdAt: '15/03/2024',
  },
  {
    id: 'usr-marcos-auditor',
    name: 'Marcos Vinícius Pires',
    email: 'marcos.pires@gruporiomais.com.br',
    department: 'Auditoria e Compliance',
    jobTitle: 'Auditor Sênior de Riscos',
    phone: '+55 (11) 96422-9018',
    documentNumber: '198.776.321-04',
    matricula: 'RIO-0322',
    role: 'visualizador',
    status: 'ativo',
    twoFactorEnabled: false,
    lastLogin: 'Ontem',
    createdAt: '01/08/2024',
  },
  {
    id: 'usr-camila-rocha',
    name: 'Dra. Camila Rocha',
    email: 'camila.rocha@gruporiomais.com.br',
    department: 'Diretoria Jurídica & Governança',
    jobTitle: 'Especialista em Direito Societário e Contratos',
    phone: '+55 (11) 99182-3401',
    documentNumber: '412.553.890-11',
    matricula: 'RIO-0480',
    role: 'editor',
    status: 'ativo',
    twoFactorEnabled: true,
    lastLogin: 'Há 2 dias',
    createdAt: '12/11/2024',
  },
  {
    id: 'usr-rodrigo-melo',
    name: 'Rodrigo Melo',
    email: 'rodrigo.melo@gruporiomais.com.br',
    department: 'Engenharia e Obras',
    jobTitle: 'Coordenador de Alianças e Fornecedores',
    phone: '+55 (21) 98711-2299',
    documentNumber: '320.119.874-50',
    matricula: 'RIO-0610',
    role: 'visualizador',
    status: 'pendente',
    twoFactorEnabled: false,
    lastLogin: 'Ainda não acessou',
    createdAt: '22/09/2026',
  },
];

export const INITIAL_API_KEYS: ApiKeyItem[] = [
  {
    id: 'key-prod-1',
    name: 'Conector ERP SAP Production Core',
    keyPrefix: 'cf_live_9a2b8c...',
    keyFull: 'cf_live_9a2b8c4d1e2f3a4b5c6d',
    environment: 'producao',
    scope: 'Leitura & Escrita',
    createdAt: '15/01/2025',
    lastUsedAt: 'Hoje às 09:12',
    status: 'ativo',
  },
  {
    id: 'key-test-1',
    name: 'Sandbox Webhook Testes CLM',
    keyPrefix: 'cf_test_7f3a1e...',
    keyFull: 'cf_test_7f3a1e9b2c8d4a6f0e1d',
    environment: 'sandbox',
    scope: 'Somente Consulta',
    createdAt: '01/02/2025',
    lastUsedAt: 'Ontem',
    status: 'ativo',
  },
];

export const INITIAL_WEBHOOKS: WebhookItem[] = [
  {
    id: 'wh-1',
    url: 'https://api.gruporiomais.internal/v1/clm/alerts',
    events: ['Vencimento de Contrato', 'Assinatura Concluída', 'Alerta de Risco'],
    status: 'ativo',
    lastDeliveryStatus: '200 OK',
    lastDeliveryAt: 'Hoje às 08:31',
  },
];

export const INITIAL_INTEGRATIONS: IntegrationConnector[] = [
  {
    id: 'receita_federal',
    name: 'Receita Federal & Sintegra (BrasilAPI)',
    category: 'receita',
    icon: 'account_balance',
    description: 'Consulta em tempo real de CNPJs, CNAEs, situação cadastral e conformidade societária.',
    connected: true,
    statusText: 'Conexão ativa (BrasilAPI v1)',
    lastSync: 'Hoje às 09:30',
    latencyMs: 142,
  },
  {
    id: 'int-docusign',
    name: 'DocuSign & Clicksign Enterprise',
    category: 'assinatura',
    icon: 'draw',
    description: 'Gestão de envelopes digitais, carimbo de tempo ICP-Brasil e trilha probatória jurídica.',
    connected: true,
    statusText: 'Conexão ativa',
    lastSync: 'Hoje às 09:15',
    latencyMs: 280,
  },
  {
    id: 'int-sap',
    name: 'SAP S/4HANA & TOTVS Protheus',
    category: 'erp',
    icon: 'hub',
    description: 'Sincronização bidirecional de pedidos de compra (PO), centros de custo e medições financeiras.',
    connected: true,
    statusText: 'Conexão ativa',
    lastSync: 'Hoje às 08:30',
    latencyMs: 310,
  },
  {
    id: 'int-slack',
    name: 'Slack & Microsoft Teams',
    category: 'comunicacao',
    icon: 'chat',
    description: 'Alertas automáticos de vencimento e canal interativo para aprovação rápida de alçadas.',
    connected: true,
    statusText: 'Conexão ativa',
    lastSync: 'Hoje às 09:40',
    latencyMs: 185,
  },
  {
    id: 'smtp_email',
    name: 'E-mail Transacional & SMTP Corporativo',
    category: 'email',
    icon: 'mail',
    description: 'Disparo de avisos de 30/60 dias, minutas e auditorias com carimbo e layout RioMais.',
    connected: true,
    statusText: 'Conexão ativa (TLS)',
    lastSync: 'Hoje às 09:55',
    latencyMs: 215,
  },
  {
    id: 'int-storage',
    name: 'Google Workspace & SharePoint',
    category: 'storage',
    icon: 'cloud_sync',
    description: 'Espelhamento automático e imutável das minutas e aditivos com hash SHA-256 no repositório.',
    connected: true,
    statusText: 'Conexão ativa',
    lastSync: 'Hoje às 07:00',
    latencyMs: 260,
  },
  {
    id: 'gemini_ai',
    name: 'Google Gemini Legal AI',
    category: 'ia',
    icon: 'psychology',
    description: 'Análise autônoma de minutas contratuais, SLAs, multas rescisórias e matriz de risco jurídico.',
    connected: true,
    statusText: 'Conexão ativa (gemini-3.8-flash)',
    lastSync: 'Hoje às 09:00',
    latencyMs: 190,
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  notice30Days: true,
  notice60Days: true,
  signaturePending7Days: true,
  aiRiskInstantAlert: true,
  legalEmail: 'juridico.corporativo@empresa.com.br',
  financeEmail: 'controladoria.contratos@empresa.com.br',
  smtpStatus: 'conectado',
  slackWebhookStatus: 'ativo',
  smsStatus: 'opcional',
  // Security settings
  twoFactorRequired: true,
  ssoEnabled: true,
  sessionTimeoutMinutes: 30,
  ipWhitelistEnabled: false,
  ipWhitelist: '189.40.112.0/24, 201.86.72.0/24',
  passwordExpirationDays: 90,
  // General settings
  companyName: 'Grupo RioMais S.A.',
  companyCnpj: '48.912.834/0001-09',
  contractPrefix: 'CTR-2025-',
  currency: 'BRL (R$)',
  timezone: 'América/São Paulo (GMT-3)',
  // Approval tiers
  tier1Limit: 50000,
  tier2Limit: 250000,
  requireDualSignatureAbove: 500000,
  granularPermissions: [
    // Contratos & Minutas
    {
      id: 'perm-contracts-view',
      category: 'contratos',
      name: 'Visualizar Contratos e Metadados',
      description: 'Consulta aos instrumentos vigentes, anexos arquivados, vigência e valores',
      administrador: 'total',
      editor: 'total',
      visualizador: 'leitura'
    },
    {
      id: 'perm-contracts-create',
      category: 'contratos',
      name: 'Cadastrar Novos Contratos',
      description: 'Criação de novos registros contratuais, upload de minutas originais e definição de prazos',
      administrador: 'total',
      editor: 'total',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-contracts-edit',
      category: 'contratos',
      name: 'Editar Metadados e Cláusulas',
      description: 'Alteração de valores, renovação de vigência, reajustes monetários e dados de fornecedor',
      administrador: 'total',
      editor: 'total',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-contracts-addendum',
      category: 'contratos',
      name: 'Elaborar Termos Aditivos',
      description: 'Criação e incorporação de minutas de aditivos com histórico de repactuação financeira',
      administrador: 'total',
      editor: 'total',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-contracts-delete',
      category: 'contratos',
      name: 'Excluir & Rescindir Contratos',
      description: 'Exclusão definitiva ou rescisão motivada de contratos e expurgo de minutas',
      administrador: 'total',
      editor: 'bloqueado',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-contracts-export',
      category: 'contratos',
      name: 'Exportar Relatórios & PDFs',
      description: 'Download de relatórios executivos em PDF/CSV e minutas integrais com assinaturas',
      administrador: 'total',
      editor: 'total',
      visualizador: 'total'
    },

    // Fornecedores & Terceiros
    {
      id: 'perm-suppliers-view',
      category: 'fornecedores',
      name: 'Consultar Diretório de Fornecedores',
      description: 'Acesso a CNPJs, certidões fiscais, contatos e score de risco de fornecedores',
      administrador: 'total',
      editor: 'total',
      visualizador: 'leitura'
    },
    {
      id: 'perm-suppliers-manage',
      category: 'fornecedores',
      name: 'Cadastrar & Atualizar Fornecedores',
      description: 'Inclusão de novas empresas parceiras, alteração de contas e certidões negativas',
      administrador: 'total',
      editor: 'total',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-suppliers-compliance',
      category: 'fornecedores',
      name: 'Homologação e Bloqueio de Compliance',
      description: 'Aprovação formal de conformidade LGPD/ESG e bloqueio administrativo de fornecedores',
      administrador: 'total',
      editor: 'total',
      visualizador: 'bloqueado'
    },

    // Assinaturas & Fluxos
    {
      id: 'perm-signatures-send',
      category: 'assinaturas',
      name: 'Enviar Envelopes para Assinatura',
      description: 'Disparo de minutas para signatários via DocuSign, Clicksign ou fluxo interno',
      administrador: 'total',
      editor: 'total',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-signatures-sign',
      category: 'assinaturas',
      name: 'Assinar com Certificado ICP-Brasil (A1/A3)',
      description: 'Aposição de assinatura digital com validade jurídica pelo signatário responsável',
      administrador: 'total',
      editor: 'total',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-signatures-cancel',
      category: 'assinaturas',
      name: 'Revogar & Anular Envelopes',
      description: 'Cancelamento definitivo de fluxo de assinatura em andamento',
      administrador: 'total',
      editor: 'bloqueado',
      visualizador: 'bloqueado'
    },

    // Inteligência Jurídica & IA
    {
      id: 'perm-ai-insights',
      category: 'ia_juridica',
      name: 'Consultar Pareceres & Análises de IA',
      description: 'Acesso aos insights preditivos, detecção de cláusulas de risco e resumos executivos',
      administrador: 'total',
      editor: 'total',
      visualizador: 'leitura'
    },
    {
      id: 'perm-ai-reanalyze',
      category: 'ia_juridica',
      name: 'Reanalisar Minutas com Motor Neural',
      description: 'Disparar reprocessamento com IA e OCR avançado em PDFs recém-anexados',
      administrador: 'total',
      editor: 'total',
      visualizador: 'bloqueado'
    },

    // Governança, Segurança & Administração
    {
      id: 'perm-gov-users',
      category: 'governanca',
      name: 'Gerenciamento de Usuários & Papéis (RBAC)',
      description: 'Convidar colaboradores, alterar permissões granulares e suspender acessos',
      administrador: 'total',
      editor: 'bloqueado',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-gov-api',
      category: 'governanca',
      name: 'Gestão de Chaves de API & Webhooks',
      description: 'Criação de tokens REST, rotação de chaves e configuração de webhooks corporativos',
      administrador: 'total',
      editor: 'bloqueado',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-gov-audit',
      category: 'governanca',
      name: 'Acesso à Trilha de Auditoria (Audit Logs)',
      description: 'Visualização de logs de segurança, carimbos de tempo, IPs e exportação pericial',
      administrador: 'total',
      editor: 'bloqueado',
      visualizador: 'bloqueado'
    },
    {
      id: 'perm-gov-security',
      category: 'governanca',
      name: 'Políticas de Segurança (2FA, SSO & IPs)',
      description: 'Configurações de obrigatoriedade de 2FA, provedores SAML/SSO e faixas de IP permitidas',
      administrador: 'total',
      editor: 'bloqueado',
      visualizador: 'bloqueado'
    }
  ],
  rbacMatrix: [
    {
      module: 'Cadastro de Fornecedores & Upload',
      subtext: 'Inserir dados básicos, certidões e minutas preliminares',
      admin: true,
      editor: true,
      visualizador: 'leitura'
    },
    {
      module: 'Homologação e Validação Cadastral',
      subtext: 'Aprovação técnica de novos fornecedores e checagem fiscal',
      admin: true,
      editor: true,
      visualizador: false
    },
    {
      module: 'Aprovação de Alçadas & Parecer Jurídico',
      subtext: 'Assinatura formal de aditivos e liberação orçamentária',
      admin: true,
      editor: true,
      visualizador: false
    },
    {
      module: 'Relatórios Estratégicos & Exportação TCO',
      subtext: 'Acesso a volumetria, saving negociado e previsão de gastos',
      admin: true,
      editor: true,
      visualizador: 'leitura'
    },
    {
      module: 'Configurações Globais & Parâmetros de IA',
      subtext: 'Chaves de API, webhooks e redefinição de gatilhos',
      admin: true,
      editor: false,
      visualizador: false
    },
    {
      module: 'Exclusão Definitiva & Trilha de Auditoria',
      subtext: 'Expurgo de registros contratuais e consulta a logs criptográficos',
      admin: true,
      editor: false,
      visualizador: false
    }
  ]
};

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'usr-lucas-teles',
  name: 'Lucas Teles',
  email: 'lucas.teles@gruporiomais.com.br',
  phone: '+55 (11) 98765-4321',
  avatarUrl: CARLOS_AVATAR,
  department: 'Jurídico Corporativo & Compliance',
  jobTitle: 'Diretor Jurídico & CLO',
  role: 'administrador',
  documentNumber: 'OAB/SP 412.980',
  documentType: 'OAB',
  timezone: 'America/Sao_Paulo (UTC-03:00)',
  language: 'pt-BR',
  bio: 'Especialista em Direito Digital, Contratos de Tecnologia e Governança Corporativa. Responsável pela aprovação de minutas, alçadas e conformidade do Grupo RioMais.',
  twoFactorEnabled: true,
  icpCertificate: {
    status: 'ativo',
    type: 'e-CPF A1',
    issuer: 'Autoridade Certificadora Certisign Brasil v5',
    serialNumber: '58:A2:3E:91:BB:72:04:8F:12',
    validUntil: '2027-11-15',
    thumbprint: 'SHA256: 4F:9C:21:8A:77:33:0B:EE:12:89:D4:56:FE:78:AB:19',
  },
  signatureInitials: 'LT',
  signatureStyle: 'rubrica_estilizada',
  notifications: {
    emailAlerts: true,
    contractExpirationAlerts: true,
    statusChangeAlerts: true,
    aiRiskAlerts: true,
    weeklyDigest: true,
    browserPush: true,
  },
};

export const initialContracts = INITIAL_CONTRACTS;
export const initialSuppliers = INITIAL_SUPPLIERS;
export const initialSettings = INITIAL_SETTINGS;
export const initialNotifications = INITIAL_NOTIFICATIONS;
export const initialAuditLogs = INITIAL_AUDIT_LOGS;
export const initialUsers = INITIAL_USERS;
export const initialApiKeys = INITIAL_API_KEYS;
export const initialWebhooks = INITIAL_WEBHOOKS;
export const initialIntegrations = INITIAL_INTEGRATIONS;
export const initialGranularPermissions = INITIAL_SETTINGS.granularPermissions || [];
export const initialUserProfile = INITIAL_USER_PROFILE;
